// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Natiga2023.Models
{
    [Keyless]
    [Table("Stage_New_Search$")]
    public partial class Stage_New_Search_
    {
        public double? seating_no { get; set; }
        [StringLength(255)]
        public string arabic_name { get; set; }
        public double? total_degree { get; set; }
        public double? student_case { get; set; }
        [StringLength(255)]
        public string student_case_desc { get; set; }
        public double? c_flage { get; set; }
    }
}